package com.castlelecs.petprofile.models

enum class Breed(val breedName: String) {
    NONE(""),
    ABYSSINIAN("Abyssinian"),
    AEGEAN("Aegean"),
    AMERICAN_BOBTAIL("American Bobtail"),
    AMERICAN_CURL("American Curl"),
    AMERICAN_SHORTHAIR("American Shorthair"),
    AMERICAN_WIREHAIR("American Wirehair"),
    ARABIAN_MAU("Arabian Mau"),
    AUSTRALIAN_MIST("Australian Mist"),
    BALINESE("Balinese"),
    BAMBINO("Bambino"),
    BENGAL("Bengal"),
    BIRMAN("Birman"),
    BOMBAY("Bombay"),
    BRITISH_LONGHAIR("British Longhair"),
    BRITISH_SHORTHAIR("British Shorthair"),
    BURMESE("Burmese"),
    BURMILLA("Burmilla"),
    CALIFORNIA_SPANGLED("California Spangled"),
    CHANTILLY_TIFFANY("Chantilly-Tiffany"),
    CHARTREUX("Chartreux"),
    CHAUSIE("Chausie"),
    CHEETOH("Cheetoh"),
    COLORPOINT_SHORTHAIR("Colorpoint Shorthair"),
    CORNISH_REX("Cornish Rex"),
    CYMRIC("Cymric"),
    CYPRUS("Cyprus"),
    DEVON_REX("Devon Rex"),
    DONSKOY("Donskoy"),
    DRAGON_LI("Dragon Li"),
    EGYPTIAN_MAU("Egyptian Mau"),
    EUROPEAN_BURMESE("European Burmese"),
    EXOTIC_SHORTHAIR("Exotic Shorthair"),
    HAVANA_BROWN("Havana Brown"),
    HIMALAYAN("Himalayan"),
    JAPANESE_BOBTAIL("Japanese Bobtail"),
    JAVANESE("Javanese"),
    KHAO_MANEE("Khao Manee"),
    KORAT("Korat"),
    KURILIAN("Kurilian"),
    LAPERM("LaPerm"),
    MAINE_COON("Maine Coon"),
    MALAYAN("Malayan"),
    MANX("Manx"),
    MUNCHKIN("Munchkin"),
    NEBELUNG("Nebelung"),
    NORWEGIAN_FOREST_CAT("Norwegian Forest Cat"),
    OCICAT("Ocicat"),
    ORIENTAL("Oriental"),
    PERSIAN("Persian"),
    PIXIE_BOB("Pixie-bob"),
    RAGAMUFFIN("Ragamuffin"),
    RAGDOLL("Ragdoll"),
    RUSSIAN_BLUE("Russian Blue"),
    SAVANNAH("Savannah"),
    SCOTTISH_FOLD("Scottish Fold"),
    SELKIRK_REX("Selkirk Rex"),
    SIAMESE("Siamese"),
    SIBERIAN("Siberian"),
    SINGAPURA("Singapura"),
    SNOWSHOE("Snowshoe"),
    SOMALI("Somali"),
    SPHYNX("Sphynx"),
    TONKINESE("Tonkinese"),
    TOYGER("Toyger"),
    TURKISH_ANGORA("Turkish Angora"),
    TURKISH_VAN("Turkish Van"),
    YORK_CHOCOLATE("York Chocolate"),
}
